import React from 'react';
import type {EffectDescriptor} from 'remotion';
import {AbsoluteFill} from 'remotion';
import {contrast} from '@remotion/effects/contrast';
import {saturation} from '@remotion/effects/saturation';
import {tint} from '@remotion/effects/tint';
import {vignette} from '@remotion/effects/vignette';
import {whiteBalance} from '@remotion/effects/white-balance';
import {levels} from '@remotion/effects/levels';
import {vibrance} from '@remotion/effects/vibrance';

/**
 * Color grades in two flavours that always agree:
 *  - `css` + `washes`: CSS filters and blend-mode color washes. Work on any HTML tree, in Studio
 *    and in renders, no WebGL. Use <Graded> to apply to a whole scene.
 *  - `effects()`: @remotion/effects stack for canvas media (<Video>, <CanvasImage>). WebGL.
 *  - `lut`: name of a .cube generated by scripts/make-lut.mjs (public/luts/<name>.cube) for the
 *    exact same look through the lut() effect. See <LutVideo>.
 */
export type GradeName = 'none' | 'teal-orange' | 'warm-film' | 'cool-noir' | 'vibrant-pop' | 'bleach-bypass' | 'matte-fade' | 'neon-night';

export type Wash = {
  readonly color: string;
  readonly blend: React.CSSProperties['mixBlendMode'];
  readonly opacity: number;
  /** CSS gradient; defaults to a full-frame solid. */
  readonly gradient?: string;
};

export type Grade = {
  readonly label: string;
  readonly css: string;
  readonly washes: readonly Wash[];
  readonly effects: () => EffectDescriptor<unknown>[];
  readonly lut: string | null;
};

export const GRADES: Record<GradeName, Grade> = {
  none: {label: 'None', css: 'none', washes: [], effects: () => [], lut: null},
  'teal-orange': {
    label: 'Teal / Orange (blockbuster)',
    css: 'contrast(1.08) saturate(1.1)',
    washes: [
      {color: '#0c6b7a', blend: 'soft-light', opacity: 0.5, gradient: 'radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 30%, #0c6b7a 100%)'},
      {color: '#ff8a3d', blend: 'overlay', opacity: 0.18, gradient: 'radial-gradient(circle at 50% 45%, #ff8a3d 0%, rgba(0,0,0,0) 65%)'},
    ],
    effects: () => [contrast({amount: 1.08}), saturation({amount: 1.1}), whiteBalance({temperature: 0.08, tint: -0.03}), vignette({amount: 0.35})],
    lut: 'teal-orange',
  },
  'warm-film': {
    label: 'Warm film',
    css: 'contrast(1.04) saturate(0.95) sepia(0.14) brightness(1.02)',
    washes: [{color: '#f2b16d', blend: 'soft-light', opacity: 0.35}],
    effects: () => [whiteBalance({temperature: 0.16}), saturation({amount: 0.95}), contrast({amount: 1.04}), vignette({amount: 0.4})],
    lut: 'warm-film',
  },
  'cool-noir': {
    label: 'Cool noir',
    css: 'contrast(1.18) saturate(0.6) brightness(0.96)',
    washes: [{color: '#1f3a5f', blend: 'soft-light', opacity: 0.55}],
    effects: () => [whiteBalance({temperature: -0.18}), saturation({amount: 0.6}), contrast({amount: 1.18}), levels({blackPoint: 0.03}), vignette({amount: 0.55})],
    lut: 'cool-noir',
  },
  'vibrant-pop': {
    label: 'Vibrant pop (social)',
    css: 'contrast(1.1) saturate(1.35) brightness(1.03)',
    washes: [],
    effects: () => [vibrance({amount: 0.5}), contrast({amount: 1.1}), levels({blackPoint: 0.02, whitePoint: 0.98})],
    lut: 'vibrant-pop',
  },
  'bleach-bypass': {
    label: 'Bleach bypass',
    css: 'contrast(1.3) saturate(0.45) brightness(1.02)',
    washes: [{color: '#d9d9d9', blend: 'overlay', opacity: 0.25}],
    effects: () => [saturation({amount: 0.45}), contrast({amount: 1.3})],
    lut: 'bleach-bypass',
  },
  'matte-fade': {
    label: 'Matte fade',
    css: 'contrast(0.92) saturate(0.9) brightness(1.04)',
    washes: [{color: '#2a2a35', blend: 'lighten', opacity: 0.22}],
    effects: () => [levels({blackPoint: -0.06, gamma: 1.05}), saturation({amount: 0.9})],
    lut: 'matte-fade',
  },
  'neon-night': {
    label: 'Neon night',
    css: 'contrast(1.15) saturate(1.3) brightness(0.95)',
    washes: [
      {color: '#5b2bff', blend: 'soft-light', opacity: 0.5, gradient: 'linear-gradient(160deg, #5b2bff 0%, rgba(0,0,0,0) 60%)'},
      {color: '#ff2bd6', blend: 'screen', opacity: 0.12, gradient: 'linear-gradient(340deg, #ff2bd6 0%, rgba(0,0,0,0) 55%)'},
    ],
    effects: () => [tint({color: '#5b2bff', amount: 0.12}), saturation({amount: 1.3}), contrast({amount: 1.15}), vignette({amount: 0.5})],
    lut: 'neon-night',
  },
};

export const GRADE_NAMES = Object.keys(GRADES) as GradeName[];

/** Wraps any scene tree in a grade: CSS filter plus blend-mode washes on top. Works without WebGL. */
export const Graded: React.FC<{readonly name: GradeName; readonly strength?: number; readonly children: React.ReactNode}> = ({name, strength = 1, children}) => {
  const grade = GRADES[name];
  if (name === 'none' || strength <= 0) return <>{children}</>;
  return (
    <AbsoluteFill>
      <AbsoluteFill style={{filter: grade.css}}>{children}</AbsoluteFill>
      {grade.washes.map((wash, i) => (
        <AbsoluteFill key={i} style={{background: wash.gradient ?? wash.color, mixBlendMode: wash.blend, opacity: wash.opacity * strength, pointerEvents: 'none'}} />
      ))}
    </AbsoluteFill>
  );
};
