import {NextRequest,NextResponse} from 'next/server';import {JobStore,database} from '@nuradi/database/jobs';import {JobSchema,statuses} from '@nuradi/schemas/index';import {requireWorker,body,errorResponse,HttpError} from '../../../lib/access';import {z} from 'zod';
const base=z.object({workerId:z.string().uuid()});const lease=base.extend({id:z.string().uuid(),leaseToken:z.string().uuid()});
export async function POST(req:NextRequest){try{requireWorker(req);const data=await body(req);const store=new JobStore(database());const worker=base.parse(data).workerId;
 if(data.op==='heartbeat'){const h=base.extend({name:z.string().max(100),node:z.string().regex(/^24\./),gitSha:z.string().regex(/^[a-f0-9]{40}$/).nullable(),machine:z.record(z.unknown())}).parse(data);await store.heartbeat(worker,h.name,h.node,h.gitSha,h.machine);return NextResponse.json({ok:true});}
 if(data.op==='claim'){const id=z.string().uuid().optional().parse(data.id);await store.failExpired();return NextResponse.json({job:await store.claim(worker,id)});}
 const l=lease.parse(data);if(data.op==='renew')return NextResponse.json({status:await store.renew(l.id,worker,l.leaseToken)??'LOST'});
 if(data.op==='progress'){const d=lease.extend({status:z.enum(statuses),progress:z.number().finite().min(0).max(1),stage:z.string().max(100),error:z.string().max(2000).nullable().optional(),artifacts:JobSchema.shape.artifacts.optional()}).parse(data);if(d.status==='COMPLETED'&&(!d.artifacts?.some(a=>a.kind==='video')||d.progress!==1))throw new HttpError(400,'Completion requires an uploaded video and full progress');if(d.artifacts?.some(a=>!a.pathname.startsWith(`renders/${d.id}/`)||new URL(a.url).hostname!==(process.env.NURADI_BLOB_HOST||'')))throw new HttpError(400,'Invalid artifact location');return NextResponse.json({job:await store.update(l.id,worker,l.leaseToken,d.status,d.progress,d.stage,d.error??null,d.artifacts??[])});}
 throw new HttpError(400,'Unknown worker operation');
 }catch(e){if(e instanceof z.ZodError)return NextResponse.json({error:'Invalid worker payload'},{status:400});return errorResponse(e);}}
