import {neon} from '@neondatabase/serverless';
import crypto from 'node:crypto';
import {transitions,type RenderRequest,type RenderJob,type JobStatus} from '@nuradi/schemas/index';
export type Query=(text:string,values?:unknown[])=>Promise<Record<string,any>[]>;
export function database():Query{const url=process.env.DATABASE_URL;if(!url)throw new Error('DATABASE_URL is not configured');const sql=neon(url);return async(text,values=[])=>await sql.query(text,values) as Record<string,any>[];}
function canonical(value:any):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
function job(row:Record<string,any>):RenderJob{return {...row.payload,gitSha:row.git_sha.trim(),schemaVersion:1,status:row.status,workerId:row.worker_id,leaseToken:row.lease_token,progress:row.progress,stage:row.stage,createdAt:new Date(row.created_at).toISOString(),updatedAt:new Date(row.updated_at).toISOString(),error:row.error,artifacts:row.artifacts};}
export class JobStore{
 constructor(private sql:Query){}
 async create(request:RenderRequest,gitSha:string){if(!/^[a-f0-9]{40}$/.test(gitSha))throw new Error('Production Git SHA is not configured');const rows=await this.sql(`WITH inserted AS (INSERT INTO render_jobs(id,project_id,payload,git_sha,status,priority,scheduled_at) VALUES($1,$2,$3::jsonb,$4,'QUEUED',$5,COALESCE($6::timestamptz,now())) ON CONFLICT(id) DO NOTHING RETURNING *),event AS (INSERT INTO render_events(render_id,status,stage,progress) SELECT id,status,stage,progress FROM inserted),outbox AS (INSERT INTO queue_outbox(render_id) SELECT id FROM inserted) SELECT * FROM inserted`,[request.id,request.projectId,JSON.stringify(request),gitSha,request.priority,request.scheduledAt??null]);if(rows[0])return job(rows[0]);const existing=await this.get(request.id);if(!existing||existing.projectId!==request.projectId||canonical(existing.sceneSpec)!==canonical(request.sceneSpec)||existing.profile!==request.profile||existing.gitSha!==gitSha)throw new Error('Request ID already belongs to another render');return existing;}
 async list(){return (await this.sql('SELECT * FROM render_jobs ORDER BY created_at DESC LIMIT 100')).map(job);}
 async get(id:string){const rows=await this.sql('SELECT * FROM render_jobs WHERE id=$1',[id]);return rows[0]?job(rows[0]):null;}
 async analytics(){return this.sql(`SELECT status,count(*)::integer AS jobs,COALESCE(avg(EXTRACT(EPOCH FROM (updated_at-created_at))),0)::float AS average_elapsed_seconds,COALESCE(sum((SELECT sum((a->>'size')::bigint) FROM jsonb_array_elements(artifacts) a)),0)::float AS output_bytes FROM render_jobs GROUP BY status`);}
 async projects(){return this.sql('SELECT id,name FROM projects ORDER BY created_at');}
 async workers(){return this.sql(`SELECT id,name,node_version,git_sha,status,last_seen,machine,(last_seen>now()-interval '45 seconds') AS online FROM render_workers ORDER BY last_seen DESC`);}
 async heartbeat(id:string,name:string,node:string,sha:string|null,machine:object){await this.sql(`INSERT INTO render_workers(id,name,node_version,git_sha,status,machine) VALUES($1,$2,$3,$4,'online',$5::jsonb) ON CONFLICT(id) DO UPDATE SET last_seen=now(),name=$2,node_version=$3,git_sha=$4,status='online',machine=$5::jsonb`,[id,name,node,sha,JSON.stringify(machine)]);}
 async claim(worker:string,requestedId?:string){const lease=crypto.randomUUID();const rows=await this.sql(`WITH picked AS (SELECT id FROM render_jobs WHERE status='QUEUED' AND scheduled_at<=now() AND ($3::uuid IS NULL OR id=$3) AND NOT EXISTS (SELECT 1 FROM render_jobs WHERE worker_id=$1 AND status IN ('CLAIMED','PREPARING','RENDERING','UPLOADING','CANCEL_REQUESTED')) ORDER BY priority DESC,created_at FOR UPDATE SKIP LOCKED LIMIT 1), updated AS (UPDATE render_jobs SET status='CLAIMED',stage='claimed',worker_id=$1,lease_token=$2,lease_until=now()+interval '90 seconds',updated_at=now() WHERE id IN (SELECT id FROM picked) RETURNING *), event AS (INSERT INTO render_events(render_id,status,stage,progress) SELECT id,status,stage,progress FROM updated) SELECT * FROM updated`,[worker,lease,requestedId??null]);return rows[0]?job(rows[0]):null;}
 async cancel(id:string){const rows=await this.sql(`WITH updated AS (UPDATE render_jobs SET status=CASE WHEN status='QUEUED' THEN 'CANCELLED' ELSE 'CANCEL_REQUESTED' END,stage='cancellation requested',updated_at=now() WHERE id=$1 AND status IN ('QUEUED','CLAIMED','PREPARING','RENDERING','UPLOADING') RETURNING *),event AS (INSERT INTO render_events(render_id,status,stage,progress) SELECT id,status,stage,progress FROM updated) SELECT * FROM updated`,[id]);return rows[0]?job(rows[0]):this.get(id);}
 async update(id:string,worker:string,lease:string,status:JobStatus,progress:number,stage:string,error:string|null=null,artifacts:RenderJob['artifacts']=[]){const previous=Object.entries(transitions).filter(([old,next])=>old===status||next.includes(status)).map(([old])=>old);const rows=await this.sql(`WITH updated AS (UPDATE render_jobs SET status=$4,progress=GREATEST(progress,$5),stage=$6,error=$7,artifacts=CASE WHEN $4='COMPLETED' THEN $8::jsonb ELSE artifacts END,lease_until=now()+interval '90 seconds',updated_at=now() WHERE id=$1 AND worker_id=$2 AND lease_token=$3 AND lease_until>now() AND status=ANY($9::text[]) AND status NOT IN ('COMPLETED','FAILED','CANCELLED') RETURNING *),event AS (INSERT INTO render_events(render_id,status,stage,progress,detail) SELECT id,status,stage,progress,jsonb_build_object('error',error) FROM updated) SELECT * FROM updated`,[id,worker,lease,status,Math.max(0,Math.min(1,progress)),stage.slice(0,100),error?.slice(0,2000)??null,JSON.stringify(artifacts),previous]);if(!rows[0])throw new Error('Lease lost, cancellation requested or invalid state transition');return job(rows[0]);}
 async renew(id:string,worker:string,lease:string){const rows=await this.sql(`UPDATE render_jobs SET lease_until=now()+interval '90 seconds' WHERE id=$1 AND worker_id=$2 AND lease_token=$3 AND lease_until>now() AND status IN ('CLAIMED','PREPARING','RENDERING','UPLOADING','CANCEL_REQUESTED') RETURNING status`,[id,worker,lease]);return rows[0]?.status as JobStatus|undefined;}
 async failExpired(){return this.sql(`WITH updated AS (UPDATE render_jobs SET status='FAILED',error='Worker lease expired; check local process before explicit retry',stage='interrupted',updated_at=now() WHERE status IN ('CLAIMED','PREPARING','RENDERING','UPLOADING','CANCEL_REQUESTED') AND lease_until<now() RETURNING *),event AS (INSERT INTO render_events(render_id,status,stage,progress,detail) SELECT id,status,stage,progress,jsonb_build_object('error',error) FROM updated) SELECT id FROM updated`);}
 async events(id:string){return this.sql('SELECT status,stage,progress,detail,created_at FROM render_events WHERE render_id=$1 ORDER BY id DESC LIMIT 200',[id]);}
 async outbox(){return this.sql(`SELECT render_id FROM queue_outbox WHERE sent_at IS NULL LIMIT 20`);}
 async dispatched(id:string){await this.sql('UPDATE queue_outbox SET sent_at=now(),attempts=attempts+1 WHERE render_id=$1',[id]);}
}
